// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkSrcApdnUat4GLqPOICTctTl67TfoOss',
    appId: '1:1088824741814:web:492111a0c76e79ec9dbb17',
    messagingSenderId: '1088824741814',
    projectId: 'bionicx-eb403',
    authDomain: 'bionicx-eb403.firebaseapp.com',
    storageBucket: 'bionicx-eb403.appspot.com',
    measurementId: 'G-785Q0DPKBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApd1MzkJc3jbg5txaG_yZC3xcnRVnAdWo',
    appId: '1:1088824741814:android:1a2443b8a2ec41ad9dbb17',
    messagingSenderId: '1088824741814',
    projectId: 'bionicx-eb403',
    storageBucket: 'bionicx-eb403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASr4hqYHWdqalET6oiecP9We5XrLwUeOc',
    appId: '1:1088824741814:ios:26a9acbfcd4a23de9dbb17',
    messagingSenderId: '1088824741814',
    projectId: 'bionicx-eb403',
    storageBucket: 'bionicx-eb403.appspot.com',
    iosBundleId: 'com.example.bionicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASr4hqYHWdqalET6oiecP9We5XrLwUeOc',
    appId: '1:1088824741814:ios:c8038e5adeb5cf809dbb17',
    messagingSenderId: '1088824741814',
    projectId: 'bionicx-eb403',
    storageBucket: 'bionicx-eb403.appspot.com',
    iosBundleId: 'com.example.bionicApp.RunnerTests',
  );
}
